#index:
#    path: /
#    controller: App\Controller\DefaultController::index
  
# the "app_lucky_number" route name is not important yet
#app_lucky_number:
#    path: /suerte/numero
#    controller: App\Controller\LuckyController::numero